# permissions for end users to edit httploadservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httploadservice-editor-role
rules:
- apiGroups:
  - load.load-operator.com
  resources:
  - httploadservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - load.load-operator.com
  resources:
  - httploadservices/status
  verbs:
  - get
