# permissions for end users to view loadservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadservice-viewer-role
rules:
- apiGroups:
  - cache.load-operator.com
  resources:
  - loadservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.load-operator.com
  resources:
  - loadservices/status
  verbs:
  - get
