# permissions for end users to edit loadservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadservice-editor-role
rules:
- apiGroups:
  - cache.load-operator.com
  resources:
  - loadservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.load-operator.com
  resources:
  - loadservices/status
  verbs:
  - get
