# permissions for end users to view metricsservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricsservice-viewer-role
rules:
- apiGroups:
  - load.load-operator.com
  resources:
  - metricsservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - load.load-operator.com
  resources:
  - metricsservices/status
  verbs:
  - get
