## Append samples you want in your CSV to this file as resources ##
resources:
- load_v1alpha1_metricsservice.yaml
- load_v1alpha1_httploadservice.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
